version: '3.9'

services:  # ← Esta línea es CRÍTICA, debe estar aquí
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    env_file:
      - .env
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile_frontend
    ports:
      - "4200:4200"
    volumes:
      - ./frontend/src_frontend:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start -- --host 0.0.0.0 --poll 2000
    stdin_open: true
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: usuarios_db
      MYSQL_USER: mateo
      MYSQL_PASSWORD: mateo123
    ports:
      - "3311:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/db_init/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql:ro

volumes:
  mysql_data: