version: '3.9'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    env_file:
      - .env
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile_frontend
    ports:
      - "4200:4200"
    volumes:
      - ./frontend/src_frontend:/usr/src/app
    command: npm start

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/db_init/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql:ro

volumes:
  mysql_data:
